<?php

/**
 * @file
 * Provides a my custom entity entity type.
 */

use Drupal\Core\Render\Element;

/**
 * Implements hook_theme().
 */
function custom_entity_migrate_theme() {
  return [
    'mycustomentity' => [
      'render element' => 'elements',
    ],
  ];
}

/**
 * Prepares variables for my custom entity templates.
 *
 * Default template: mycustomentity.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the my custom entity
 *     information and any fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_mycustomentity(array &$variables) {
  $variables['view_mode'] = $variables['elements']['#view_mode'];
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}
